addons:
  apt:
    packages:
    - autopoint

language: c

matrix:
  include:
    # Linux - amd64
    - os: linux
      arch: amd64
      env:
        - BRANCH=0.20.2
    - os: linux
      arch: amd64
      env:
        - BRANCH=1.0.6
    - os: linux
      arch: amd64
      env:
        - BRANCH=1.2.4
    - os: linux
      arch: amd64
      env:
        - BRANCH=devel
    # Linux - arm64
    - os: linux
      arch: arm64
      env:
        - BRANCH=1.2.4
    # Linux - ppc64
    - os: linux
      arch: ppc64le
      env:
        - BRANCH=1.2.4
    # macOS - amd64
    - os: osx
      env:
        - BRANCH=0.20.2
    - os: osx
      env:
        - BRANCH=1.2.4
    - os: osx
      env:
        - BRANCH=1.0.6
    - os: osx
      env:
        - BRANCH=devel
    # windows - amd64
    - os: windows
      env:
        - BRANCH=0.20.2
    - os: windows
      env:
        - BRANCH=1.2.4
    - os: windows
      env:
        - BRANCH=1.0.6
    - os: windows
      env:
        - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - export PATH="~/Nim/bin:/usr/local/opt/gettext/bin:$PATH"
  - |
    # Use choosenim if already available for platform, otherwise build nim
    case $TRAVIS_CPU_ARCH in
      amd64 )
        curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
        source travis.sh
        ;;
      * )
        pushd ~
        if [[ "${BRANCH}" =~ [0-9] ]]; then
          # Tag
          export COMMITLIKE="v${BRANCH}"
        else
          export COMMITLIKE="${BRANCH"
        fi
        git clone -b "${COMMITLIKE}" --single-branch https://github.com/nim-lang/Nim.git
        pushd Nim
        sh build_all.sh
        popd
        popd
        ;;
    esac

script:
  - set -e
  - nimble develop -y
  - nimble test
  - nimble --verbose --nimbleDir:`pwd`/build/fakenimble install nimterop@#head -y
